title: Dániel Farkas | Cloud Projects Portfolio
logo: files/cropped_circle_image (1).png
description: A portfolio showcasing my Azure Cloud Administration Projects
theme: jekyll-theme-minimal

---

➡ [View Step-by-Step Guide](azure_project_documentation.md)
