title: Dániel Farkas | Cloud Projects Portfolio
logo: /Azureproject/files/cropped_circle_image.png
description: A portfolio showcasing my Azure Cloud Administration Projects
theme: jekyll-theme-minimal
